export type CountryDial = {
  iso: string;
  name: string;
  dial: string;
};

const countryList: CountryDial[] = [
  { iso: "af", name: "Afghanistan", dial: "+93" },
  { iso: "al", name: "Albania", dial: "+355" },
  { iso: "dz", name: "Algeria", dial: "+213" },
  { iso: "ad", name: "Andorra", dial: "+376" },
  { iso: "ao", name: "Angola", dial: "+244" },
  { iso: "ag", name: "Antigua and Barbuda", dial: "+1268" },
  { iso: "ar", name: "Argentina", dial: "+54" },
  { iso: "am", name: "Armenia", dial: "+374" },
  { iso: "au", name: "Australia", dial: "+61" },
  { iso: "at", name: "Austria", dial: "+43" },
  { iso: "az", name: "Azerbaijan", dial: "+994" },
  { iso: "bs", name: "Bahamas", dial: "+1242" },
  { iso: "bh", name: "Bahrain", dial: "+973" },
  { iso: "bd", name: "Bangladesh", dial: "+880" },
  { iso: "bb", name: "Barbados", dial: "+1246" },
  { iso: "by", name: "Belarus", dial: "+375" },
  { iso: "be", name: "Belgium", dial: "+32" },
  { iso: "bz", name: "Belize", dial: "+501" },
  { iso: "bj", name: "Benin", dial: "+229" },
  { iso: "bt", name: "Bhutan", dial: "+975" },
  { iso: "bo", name: "Bolivia", dial: "+591" },
  { iso: "ba", name: "Bosnia and Herzegovina", dial: "+387" },
  { iso: "bw", name: "Botswana", dial: "+267" },
  { iso: "br", name: "Brazil", dial: "+55" },
  { iso: "bn", name: "Brunei", dial: "+673" },
  { iso: "bg", name: "Bulgaria", dial: "+359" },
  { iso: "bf", name: "Burkina Faso", dial: "+226" },
  { iso: "bi", name: "Burundi", dial: "+257" },
  { iso: "kh", name: "Cambodia", dial: "+855" },
  { iso: "cm", name: "Cameroon", dial: "+237" },
  { iso: "ca", name: "Canada", dial: "+1" },
  { iso: "cv", name: "Cape Verde", dial: "+238" },
  { iso: "cf", name: "Central African Republic", dial: "+236" },
  { iso: "td", name: "Chad", dial: "+235" },
  { iso: "cl", name: "Chile", dial: "+56" },
  { iso: "cn", name: "China", dial: "+86" },
  { iso: "co", name: "Colombia", dial: "+57" },
  { iso: "km", name: "Comoros", dial: "+269" },
  { iso: "cg", name: "Congo", dial: "+242" },
  { iso: "cr", name: "Costa Rica", dial: "+506" },
  { iso: "hr", name: "Croatia", dial: "+385" },
  { iso: "cu", name: "Cuba", dial: "+53" },
  { iso: "cy", name: "Cyprus", dial: "+357" },
  { iso: "cz", name: "Czechia", dial: "+420" },
  { iso: "cd", name: "Democratic Republic of the Congo", dial: "+243" },
  { iso: "dk", name: "Denmark", dial: "+45" },
  { iso: "dj", name: "Djibouti", dial: "+253" },
  { iso: "dm", name: "Dominica", dial: "+1767" },
  { iso: "do", name: "Dominican Republic", dial: "+1809" },
  { iso: "ec", name: "Ecuador", dial: "+593" },
  { iso: "eg", name: "Egypt", dial: "+20" },
  { iso: "sv", name: "El Salvador", dial: "+503" },
  { iso: "gq", name: "Equatorial Guinea", dial: "+240" },
  { iso: "er", name: "Eritrea", dial: "+291" },
  { iso: "ee", name: "Estonia", dial: "+372" },
  { iso: "sz", name: "Eswatini", dial: "+268" },
  { iso: "et", name: "Ethiopia", dial: "+251" },
  { iso: "fj", name: "Fiji", dial: "+679" },
  { iso: "fi", name: "Finland", dial: "+358" },
  { iso: "fr", name: "France", dial: "+33" },
  { iso: "ga", name: "Gabon", dial: "+241" },
  { iso: "gm", name: "Gambia", dial: "+220" },
  { iso: "ge", name: "Georgia", dial: "+995" },
  { iso: "de", name: "Germany", dial: "+49" },
  { iso: "gh", name: "Ghana", dial: "+233" },
  { iso: "gr", name: "Greece", dial: "+30" },
  { iso: "gd", name: "Grenada", dial: "+1473" },
  { iso: "gt", name: "Guatemala", dial: "+502" },
  { iso: "gn", name: "Guinea", dial: "+224" },
  { iso: "gw", name: "Guinea-Bissau", dial: "+245" },
  { iso: "gy", name: "Guyana", dial: "+592" },
  { iso: "ht", name: "Haiti", dial: "+509" },
  { iso: "hn", name: "Honduras", dial: "+504" },
  { iso: "hk", name: "Hong Kong", dial: "+852" },
  { iso: "hu", name: "Hungary", dial: "+36" },
  { iso: "is", name: "Iceland", dial: "+354" },
  { iso: "in", name: "India", dial: "+91" },
  { iso: "id", name: "Indonesia", dial: "+62" },
  { iso: "ir", name: "Iran", dial: "+98" },
  { iso: "iq", name: "Iraq", dial: "+964" },
  { iso: "ie", name: "Ireland", dial: "+353" },
  { iso: "il", name: "Israel", dial: "+972" },
  { iso: "it", name: "Italy", dial: "+39" },
  { iso: "ci", name: "Ivory Coast", dial: "+225" },
  { iso: "jm", name: "Jamaica", dial: "+1876" },
  { iso: "jp", name: "Japan", dial: "+81" },
  { iso: "jo", name: "Jordan", dial: "+962" },
  { iso: "kz", name: "Kazakhstan", dial: "+7" },
  { iso: "ke", name: "Kenya", dial: "+254" },
  { iso: "ki", name: "Kiribati", dial: "+686" },
  { iso: "xk", name: "Kosovo", dial: "+383" },
  { iso: "kw", name: "Kuwait", dial: "+965" },
  { iso: "kg", name: "Kyrgyzstan", dial: "+996" },
  { iso: "la", name: "Laos", dial: "+856" },
  { iso: "lv", name: "Latvia", dial: "+371" },
  { iso: "lb", name: "Lebanon", dial: "+961" },
  { iso: "ls", name: "Lesotho", dial: "+266" },
  { iso: "lr", name: "Liberia", dial: "+231" },
  { iso: "ly", name: "Libya", dial: "+218" },
  { iso: "li", name: "Liechtenstein", dial: "+423" },
  { iso: "lt", name: "Lithuania", dial: "+370" },
  { iso: "lu", name: "Luxembourg", dial: "+352" },
  { iso: "mo", name: "Macao", dial: "+853" },
  { iso: "mg", name: "Madagascar", dial: "+261" },
  { iso: "mw", name: "Malawi", dial: "+265" },
  { iso: "my", name: "Malaysia", dial: "+60" },
  { iso: "mv", name: "Maldives", dial: "+960" },
  { iso: "ml", name: "Mali", dial: "+223" },
  { iso: "mt", name: "Malta", dial: "+356" },
  { iso: "mh", name: "Marshall Islands", dial: "+692" },
  { iso: "mr", name: "Mauritania", dial: "+222" },
  { iso: "mu", name: "Mauritius", dial: "+230" },
  { iso: "mx", name: "Mexico", dial: "+52" },
  { iso: "fm", name: "Micronesia", dial: "+691" },
  { iso: "md", name: "Moldova", dial: "+373" },
  { iso: "mc", name: "Monaco", dial: "+377" },
  { iso: "mn", name: "Mongolia", dial: "+976" },
  { iso: "me", name: "Montenegro", dial: "+382" },
  { iso: "ma", name: "Morocco", dial: "+212" },
  { iso: "mz", name: "Mozambique", dial: "+258" },
  { iso: "mm", name: "Myanmar", dial: "+95" },
  { iso: "na", name: "Namibia", dial: "+264" },
  { iso: "nr", name: "Nauru", dial: "+674" },
  { iso: "np", name: "Nepal", dial: "+977" },
  { iso: "nl", name: "Netherlands", dial: "+31" },
  { iso: "nz", name: "New Zealand", dial: "+64" },
  { iso: "ni", name: "Nicaragua", dial: "+505" },
  { iso: "ne", name: "Niger", dial: "+227" },
  { iso: "ng", name: "Nigeria", dial: "+234" },
  { iso: "kp", name: "North Korea", dial: "+850" },
  { iso: "mk", name: "North Macedonia", dial: "+389" },
  { iso: "no", name: "Norway", dial: "+47" },
  { iso: "om", name: "Oman", dial: "+968" },
  { iso: "pk", name: "Pakistan", dial: "+92" },
  { iso: "pw", name: "Palau", dial: "+680" },
  { iso: "ps", name: "Palestine", dial: "+970" },
  { iso: "pa", name: "Panama", dial: "+507" },
  { iso: "pg", name: "Papua New Guinea", dial: "+675" },
  { iso: "py", name: "Paraguay", dial: "+595" },
  { iso: "pe", name: "Peru", dial: "+51" },
  { iso: "ph", name: "Philippines", dial: "+63" },
  { iso: "pl", name: "Poland", dial: "+48" },
  { iso: "pt", name: "Portugal", dial: "+351" },
  { iso: "pr", name: "Puerto Rico", dial: "+1787" },
  { iso: "qa", name: "Qatar", dial: "+974" },
  { iso: "ro", name: "Romania", dial: "+40" },
  { iso: "ru", name: "Russia", dial: "+7" },
  { iso: "rw", name: "Rwanda", dial: "+250" },
  { iso: "kn", name: "Saint Kitts and Nevis", dial: "+1869" },
  { iso: "lc", name: "Saint Lucia", dial: "+1758" },
  { iso: "vc", name: "Saint Vincent and the Grenadines", dial: "+1784" },
  { iso: "ws", name: "Samoa", dial: "+685" },
  { iso: "sm", name: "San Marino", dial: "+378" },
  { iso: "st", name: "Sao Tome and Principe", dial: "+239" },
  { iso: "sa", name: "Saudi Arabia", dial: "+966" },
  { iso: "sn", name: "Senegal", dial: "+221" },
  { iso: "rs", name: "Serbia", dial: "+381" },
  { iso: "sc", name: "Seychelles", dial: "+248" },
  { iso: "sl", name: "Sierra Leone", dial: "+232" },
  { iso: "sg", name: "Singapore", dial: "+65" },
  { iso: "sk", name: "Slovakia", dial: "+421" },
  { iso: "si", name: "Slovenia", dial: "+386" },
  { iso: "sb", name: "Solomon Islands", dial: "+677" },
  { iso: "so", name: "Somalia", dial: "+252" },
  { iso: "za", name: "South Africa", dial: "+27" },
  { iso: "kr", name: "South Korea", dial: "+82" },
  { iso: "ss", name: "South Sudan", dial: "+211" },
  { iso: "es", name: "Spain", dial: "+34" },
  { iso: "lk", name: "Sri Lanka", dial: "+94" },
  { iso: "sd", name: "Sudan", dial: "+249" },
  { iso: "sr", name: "Suriname", dial: "+597" },
  { iso: "se", name: "Sweden", dial: "+46" },
  { iso: "ch", name: "Switzerland", dial: "+41" },
  { iso: "sy", name: "Syria", dial: "+963" },
  { iso: "tw", name: "Taiwan", dial: "+886" },
  { iso: "tj", name: "Tajikistan", dial: "+992" },
  { iso: "tz", name: "Tanzania", dial: "+255" },
  { iso: "th", name: "Thailand", dial: "+66" },
  { iso: "tl", name: "Timor-Leste", dial: "+670" },
  { iso: "tg", name: "Togo", dial: "+228" },
  { iso: "to", name: "Tonga", dial: "+676" },
  { iso: "tt", name: "Trinidad and Tobago", dial: "+1868" },
  { iso: "tn", name: "Tunisia", dial: "+216" },
  { iso: "tr", name: "Turkey", dial: "+90" },
  { iso: "tm", name: "Turkmenistan", dial: "+993" },
  { iso: "tv", name: "Tuvalu", dial: "+688" },
  { iso: "ug", name: "Uganda", dial: "+256" },
  { iso: "ua", name: "Ukraine", dial: "+380" },
  { iso: "ae", name: "United Arab Emirates", dial: "+971" },
  { iso: "gb", name: "United Kingdom", dial: "+44" },
  { iso: "us", name: "United States", dial: "+1" },
  { iso: "uy", name: "Uruguay", dial: "+598" },
  { iso: "uz", name: "Uzbekistan", dial: "+998" },
  { iso: "vu", name: "Vanuatu", dial: "+678" },
  { iso: "va", name: "Vatican City", dial: "+379" },
  { iso: "ve", name: "Venezuela", dial: "+58" },
  { iso: "vn", name: "Vietnam", dial: "+84" },
  { iso: "ye", name: "Yemen", dial: "+967" },
  { iso: "zm", name: "Zambia", dial: "+260" },
  { iso: "zw", name: "Zimbabwe", dial: "+263" },
];

export const countries: CountryDial[] = [...countryList].sort((a, b) =>
  a.name.localeCompare(b.name),
);

export function countryByIso(iso: string | null | undefined) {
  if (!iso) return null;
  return countries.find((country) => country.iso === iso.toLowerCase()) ?? null;
}

export function flagSrc(iso: string) {
  return `https://flagcdn.com/w160/${iso.toLowerCase()}.png`;
}

/**
 * Turns whatever a visitor typed into the national digits to append to a
 * dial code: strips formatting, an already-typed "+972" / "00972" prefix, and
 * the trunk-prefix zeros people add out of habit (e.g. 050… → 50…).
 */
export function nationalDigits(raw: string, dial: string) {
  const typed = raw.trim();
  let digits = typed.replace(/\D/g, "");
  const dialDigits = dial.replace(/\D/g, "");

  if (typed.startsWith("+") || typed.startsWith("00")) {
    digits = digits.replace(/^00/, "");
    if (digits.startsWith(dialDigits)) digits = digits.slice(dialDigits.length);
  }

  return digits.replace(/^0+/, "");
}
